idf_component_register(
    SRCS
        "wt_app_web.c"
    INCLUDE_DIRS 
        "include"
    REQUIRES
        spiffs
        esp_partition
        esp_timer
        esp_http_server
        app_update
        spi_flash
        esp_driver_tsens
        json
        wt_app_log
        wt_app_wifi
)
